default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# In production a JSON-capable RDBMS is recommended (jsonb).
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  database: <%= ENV.fetch("DPP_DB_NAME", "dpp_service_production") %>
  username: <%= ENV["DPP_DB_USER"] %>
  password: <%= ENV["DPP_DB_PASSWORD"] %>
  host: <%= ENV.fetch("DPP_DB_HOST", "localhost") %>
